var tipos__maquinas__reportes__x__indicadores__metricas__reportes_8py =
[
    [ "tipos_maquinas_reportes_x_indicadores_metricas_reportes.TiposMaquinasReportesXIndicadoresMetricasReportesCreateAPIView", "classtipos__maquinas__reportes__x__indicadores__metricas__reportes_1_1_tipos_maquinas_reportes_x755b401890d27ed8212434069f93c06d.html", null ],
    [ "tipos_maquinas_reportes_x_indicadores_metricas_reportes.TiposMaquinasReportesXIndicadoresMetricasReportesUpdateAPIView", "classtipos__maquinas__reportes__x__indicadores__metricas__reportes_1_1_tipos_maquinas_reportes_x0adbb8a00174610740da26fa599cc49a.html", null ],
    [ "tipos_maquinas_reportes_x_indicadores_metricas_reportes.TiposMaquinasReportesXIndicadoresMetricasReportesDestroyAPIView", "classtipos__maquinas__reportes__x__indicadores__metricas__reportes_1_1_tipos_maquinas_reportes_x7f65ee05825dbf35c65070189d49af27.html", null ],
    [ "urls_controller_tipos_maquinas_reportes_x_indicadores_metricas_reportes", "tipos__maquinas__reportes__x__indicadores__metricas__reportes_8py.html#a68d0f41d14bc9565a45d0d72079eddf5", null ]
];